package com.app.pojo;
// Generated 17 Jan, 2018 5:54:12 PM by Hibernate Tools 5.2.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Person generated by hbm2java
 */
@Entity
@Table(name = "person", catalog = "assign1db")
public class Person implements java.io.Serializable {

	private Integer id;
	private String fname;
	private String mname;
	private String lname;
	private String hobby;

	public Person() {
	}

	public Person(String fname, String mname, String lname, String hobby) {
		this.fname = fname;
		this.mname = mname;
		this.lname = lname;
		this.hobby = hobby;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "Fname", length = 50)
	public String getFname() {
		return this.fname;
	}

	public void setFname(String fname) {
		this.fname = fname;
	}

	@Column(name = "Mname", length = 50)
	public String getMname() {
		return this.mname;
	}

	public void setMname(String mname) {
		this.mname = mname;
	}

	@Column(name = "Lname", length = 50)
	public String getLname() {
		return this.lname;
	}

	public void setLname(String lname) {
		this.lname = lname;
	}

	@Column(name = "hobby", length = 500)
	public String getHobby() {
		return this.hobby;
	}

	public void setHobby(String hobby) {
		this.hobby = hobby;
	}

	@Override
	public String toString() {
		return "Person [id=" + id + ", fname=" + fname + ", mname=" + mname + ", lname=" + lname + ", hobby=" + hobby
				+ "]";
	}

}
